version: '3.8'
services:
  auth-service:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - erp-net
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - erp-net
networks:
  erp-net:
    external: false
volumes:
  pgdata: 