version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - erp-net

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    networks:
      - erp-net

  procurement-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: procurement
    ports:
      - '5433:5432'
    volumes:
      - procurement_pgdata:/var/lib/postgresql/data
    networks:
      - erp-net

  sales-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales
    ports:
      - '5434:5432'
    volumes:
      - sales_pgdata:/var/lib/postgresql/data
    networks:
      - erp-net

  stock-management-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_management
    ports:
      - '5435:5432'
    volumes:
      - stock_management_pgdata:/var/lib/postgresql/data
    networks:
      - erp-net

  project-management-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_management
    ports:
      - '5436:5432'
    volumes:
      - project_management_pgdata:/var/lib/postgresql/data
    networks:
      - erp-net

  auth-service-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    ports:
      - '5437:5432'
    volumes:
      - auth_service_pgdata:/var/lib/postgresql/data
    networks:
      - erp-net

  procurement:
    build: ./procurement
    env_file:
      - ./procurement/.env
    depends_on:
      - procurement-db
      - kafka
    networks:
      - erp-net
    environment:
      - POSTGRES_HOST=procurement-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=procurement
      - KAFKA_BROKER=kafka:9092

  sales:
    build: ./sales
    env_file:
      - ./sales/.env
    depends_on:
      - sales-db
      - kafka
    networks:
      - erp-net
    environment:
      - POSTGRES_HOST=sales-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales
      - KAFKA_BROKER=kafka:9092

  stock-management:
    build: ./stock-management
    env_file:
      - ./stock-management/.env
    depends_on:
      - stock-management-db
      - kafka
    networks:
      - erp-net
    environment:
      - POSTGRES_HOST=stock-management-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_management
      - KAFKA_BROKER=kafka:9092

  project-management:
    build: ./project-management
    env_file:
      - ./project-management/.env
    depends_on:
      - project-management-db
      - kafka
    networks:
      - erp-net
    environment:
      - POSTGRES_HOST=project-management-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_management
      - KAFKA_BROKER=kafka:9092

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - auth-service-db
      - kafka
    networks:
      - erp-net
    environment:
      - POSTGRES_HOST=auth-service-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_service
      - KAFKA_BROKER=kafka:9092

networks:
  erp-net:
    driver: bridge

volumes:
  procurement_pgdata:
  sales_pgdata:
  stock_management_pgdata:
  project_management_pgdata:
  auth_service_pgdata: 